sonar.projectKey=identity-backend
sonar.projectName=identity-backend
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=cover.out
sonar.go.tests.reportPaths=tests.out
sonar.sourceEncoding=UTF-8
