apiVersion: v1
kind: ConfigMap
metadata:
  name: xcluster-config
  namespace: identity-db
data:
  stream_name: "c2-to-c1"
  remote_masters: "yb-master-c2.apps.cluster-4rnqf.4rnqf.sandbox3259.opentlc.com:443"
