apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kube-linter
  namespace: cicd
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: stackrox/kube-linter:0.7.4-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        kube-linter lint platform pipelines clusters
