apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: sonar-operator
  namespace: openshift-operators
spec:
  channel: alpha
  name: sonar-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
