apiVersion: v1
kind: ConfigMap
metadata:
  name: xcluster-config
  namespace: identity-db
data:
  stream_name: "c1-to-c2"
  remote_masters: "yb-master-c1.apps.cluster-6b699.6b699.sandbox3565.opentlc.com:443"
